### ISSUE TITLE
graphcool-cli does not get content of function handlers

### ISSUE THREAD

**Issue by danmkent** [graphcool/api-bugs#254]
**What is the current behavior?**

When using graphcool-cli version `1.3.8`, doing a `graphcool pull` gets a `graphcool.yml` file that is missing the code for function handlers:

```
functions:
  add:
    handler: {}
    type: schemaExtension
  CheckVersion:
    handler: {}
    type: operationBefore
    operation: Versioned.update
  TestJson:
    handler: {}
    type: schemaExtension
```

**What is the expected behavior?**

Code for function handlers is included, either directly or with a reference to a separate file (like what happens for permissions queries)
