### ISSUE TITLE
automatically inject shortlived (5 minutes) pat in all functions context

### ISSUE THREAD

**Issue by sorenbs** [graphcool/api-bugs#265]

**Comment by kbrandwijk** [comment]
That doesn't play well with the FR to have more control over the permissions given to a PAT...

**Comment by sorenbs** [comment]
That's correct @kbrandwijk 

We need a mechanism to specify the pat given to a function context. What do you think of something like this?

```yaml
functions:
  authenticteCustomer:
    handler:
      code:
        src: ./code/authenticate.js
    context:
      rootToken: authenticate
    type: schemaExtension
    schema: ./code/authenticate.graphql

rootTokens:
- authenticate
```
